# Change these first
owner: edu-red # Your GitHub organization or username, where this repository lives
repo: DGE-GOV # The name of this repository

sites:
  - name: Webmail-DGE
    url: http://webmail.mendoza.edu.ar
    icon: https://www.mendoza.edu.ar/favicon.ico
  - name: Portal-DGE
    url: https://www.mendoza.edu.ar
    icon: https://www.mendoza.edu.ar/favicon.ico
  - name: Webmail-GOV
    url: https://rcmail.mendoza.gov.ar/
    icon: https://rcmail.mendoza.gov.ar/favicon.ico
  - name: Portal-GOV
    url: https://www.mendoza.gov.ar
    icon: https://www.mendoza.gov.ar/favicon.ico
    
assignees:
  - edu-red

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /DGE-GOV
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name:  Eduardo Romero
  introTitle: "**Monitor de servicios**"
  introMessage: -[Dirección General de Escuelas](https://www.mendoza.edu.ar), [Gobierno de Mendoza](https://www.mendoza.gov.ar)-
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
